### ISSUE TITLE
Extract a message within a timestamp

### ISSUE THREAD

**Issue by xrkong** [Geekgineer/ros2_bag_exporter#1]
Thank you for your code!
I'm wondering if there is any development plan to implement a function that extracts all messages within a given timestamp?

**Comment by Geekgineer** [comment]
Hi yes, it's in the development plan stay tuned!

**Comment by Geekgineer** [comment]
For reference, I won't develop the split with a timestamp soon. 

But I have provided a splitting tool you can split the part needed from the ros2 bag then export the content:

https://github.com/Geekgineer/ros2_bag_exporter/tree/main/ros2bag_splitter
